//
//  ListPresenter.swift
//  iOSMeetup
//
//  Created by Iván on 4/22/19.
//  Copyright (c) 2019 dequin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentFetchedGroups(response: List.FetchGroups.Response)
}

class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?

    // MARK: Present Fetched Groups

    func presentFetchedGroups(response: List.FetchGroups.Response) {
        var displayedGroups: [List.FetchGroups.ViewModel.DisplayedGroup] = []
        for group in response.groups {
            let displayGroup = List.FetchGroups.ViewModel.DisplayedGroup(
                name: group.name,
                city: group.city
            )
            displayedGroups.append(displayGroup)
        }
        let viewModel = List.FetchGroups.ViewModel(displayedGroups: displayedGroups)
        viewController?.displayGroups(viewModel: viewModel)
    }
}
