//
//  ListWorker.swift
//  iOSMeetup
//
//  Created by Iván on 4/22/19.
//  Copyright (c) 2019 dequin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Keys
import SwiftyJSON
import UIKit

class ListWorker {
    let apiKeyString = "API_KEY"
    let groupsURL = "https://api.meetup.com/2/groups?lat=51.509980&lon=-0.133700&page=20&key=API_KEY"

    private let session = URLSession(configuration: .default)

    func doSomeWork(completion: @escaping (([Group]) -> Void)) {
        let keys = IOSMeetupKeys()
        let endpoint = URL(string: groupsURL.replacingOccurrences(of: apiKeyString, with: keys.meetupApiKey))!

        let task = session.dataTask(with: URLRequest(url: endpoint)) { data, _, error in
            if let data = data {
                do {
                    let json = try JSON(data: data)
                    if let groups = (json["results"].array?.map { Group(json: $0) }) {
                        completion(groups)
                    }

                } catch let jsonErr {
                    debugPrint(jsonErr)
                }
            } else if let error = error {
                debugPrint(error)
            }
        }
        task.resume()
    }
}
