//
//  ListInteractor.swift
//  iOSMeetup
//
//  Created by Iván on 4/22/19.
//  Copyright (c) 2019 dequin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic {
    func fetchGroups(request: List.FetchGroups.Request)
}

protocol ListDataStore {
    var groups: [Group]? { get set }
}

class ListInteractor: ListBusinessLogic, ListDataStore {
    var presenter: ListPresentationLogic?
    var worker: ListWorker?

    var groups: [Group]?

    // MARK: Fetch Groups

    func fetchGroups(request: List.FetchGroups.Request) {
        worker = ListWorker()
        worker?.doSomeWork(completion: { groups in
            self.groups = groups

            let response = List.FetchGroups.Response(groups: groups)
            self.presenter?.presentFetchedGroups(response: response)
        })
    }
}
